# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vini84200/projetos/compiladores

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vini84200/projetos/compiladores

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vini84200/projetos/compiladores/CMakeFiles /home/vini84200/projetos/compiladores//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vini84200/projetos/compiladores/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Compiladores

# Build rule for target.
Compiladores: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Compiladores
.PHONY : Compiladores

# fast build rule for target.
Compiladores/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/build
.PHONY : Compiladores/fast

parser.o: parser.c.o
.PHONY : parser.o

# target to build an object file
parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/parser.c.o
.PHONY : parser.c.o

parser.i: parser.c.i
.PHONY : parser.i

# target to preprocess a source file
parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/parser.c.i
.PHONY : parser.c.i

parser.s: parser.c.s
.PHONY : parser.s

# target to generate assembly for a file
parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/parser.c.s
.PHONY : parser.c.s

scanner.o: scanner.c.o
.PHONY : scanner.o

# target to build an object file
scanner.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/scanner.c.o
.PHONY : scanner.c.o

scanner.i: scanner.c.i
.PHONY : scanner.i

# target to preprocess a source file
scanner.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/scanner.c.i
.PHONY : scanner.c.i

scanner.s: scanner.c.s
.PHONY : scanner.s

# target to generate assembly for a file
scanner.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/scanner.c.s
.PHONY : scanner.c.s

src/argumentParser.o: src/argumentParser.c.o
.PHONY : src/argumentParser.o

# target to build an object file
src/argumentParser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/argumentParser.c.o
.PHONY : src/argumentParser.c.o

src/argumentParser.i: src/argumentParser.c.i
.PHONY : src/argumentParser.i

# target to preprocess a source file
src/argumentParser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/argumentParser.c.i
.PHONY : src/argumentParser.c.i

src/argumentParser.s: src/argumentParser.c.s
.PHONY : src/argumentParser.s

# target to generate assembly for a file
src/argumentParser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/argumentParser.c.s
.PHONY : src/argumentParser.c.s

src/ast.o: src/ast.c.o
.PHONY : src/ast.o

# target to build an object file
src/ast.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/ast.c.o
.PHONY : src/ast.c.o

src/ast.i: src/ast.c.i
.PHONY : src/ast.i

# target to preprocess a source file
src/ast.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/ast.c.i
.PHONY : src/ast.c.i

src/ast.s: src/ast.c.s
.PHONY : src/ast.s

# target to generate assembly for a file
src/ast.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/ast.c.s
.PHONY : src/ast.c.s

src/errorHandler.o: src/errorHandler.c.o
.PHONY : src/errorHandler.o

# target to build an object file
src/errorHandler.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/errorHandler.c.o
.PHONY : src/errorHandler.c.o

src/errorHandler.i: src/errorHandler.c.i
.PHONY : src/errorHandler.i

# target to preprocess a source file
src/errorHandler.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/errorHandler.c.i
.PHONY : src/errorHandler.c.i

src/errorHandler.s: src/errorHandler.c.s
.PHONY : src/errorHandler.s

# target to generate assembly for a file
src/errorHandler.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/errorHandler.c.s
.PHONY : src/errorHandler.c.s

src/funcCode.o: src/funcCode.cpp.o
.PHONY : src/funcCode.o

# target to build an object file
src/funcCode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/funcCode.cpp.o
.PHONY : src/funcCode.cpp.o

src/funcCode.i: src/funcCode.cpp.i
.PHONY : src/funcCode.i

# target to preprocess a source file
src/funcCode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/funcCode.cpp.i
.PHONY : src/funcCode.cpp.i

src/funcCode.s: src/funcCode.cpp.s
.PHONY : src/funcCode.s

# target to generate assembly for a file
src/funcCode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/funcCode.cpp.s
.PHONY : src/funcCode.cpp.s

src/generateAssembly.o: src/generateAssembly.c.o
.PHONY : src/generateAssembly.o

# target to build an object file
src/generateAssembly.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/generateAssembly.c.o
.PHONY : src/generateAssembly.c.o

src/generateAssembly.i: src/generateAssembly.c.i
.PHONY : src/generateAssembly.i

# target to preprocess a source file
src/generateAssembly.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/generateAssembly.c.i
.PHONY : src/generateAssembly.c.i

src/generateAssembly.s: src/generateAssembly.c.s
.PHONY : src/generateAssembly.s

# target to generate assembly for a file
src/generateAssembly.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/generateAssembly.c.s
.PHONY : src/generateAssembly.c.s

src/generateCode.o: src/generateCode.c.o
.PHONY : src/generateCode.o

# target to build an object file
src/generateCode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/generateCode.c.o
.PHONY : src/generateCode.c.o

src/generateCode.i: src/generateCode.c.i
.PHONY : src/generateCode.i

# target to preprocess a source file
src/generateCode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/generateCode.c.i
.PHONY : src/generateCode.c.i

src/generateCode.s: src/generateCode.c.s
.PHONY : src/generateCode.s

# target to generate assembly for a file
src/generateCode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/generateCode.c.s
.PHONY : src/generateCode.c.s

src/graphBlock.o: src/graphBlock.c.o
.PHONY : src/graphBlock.o

# target to build an object file
src/graphBlock.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/graphBlock.c.o
.PHONY : src/graphBlock.c.o

src/graphBlock.i: src/graphBlock.c.i
.PHONY : src/graphBlock.i

# target to preprocess a source file
src/graphBlock.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/graphBlock.c.i
.PHONY : src/graphBlock.c.i

src/graphBlock.s: src/graphBlock.c.s
.PHONY : src/graphBlock.s

# target to generate assembly for a file
src/graphBlock.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/graphBlock.c.s
.PHONY : src/graphBlock.c.s

src/hash.o: src/hash.c.o
.PHONY : src/hash.o

# target to build an object file
src/hash.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/hash.c.o
.PHONY : src/hash.c.o

src/hash.i: src/hash.c.i
.PHONY : src/hash.i

# target to preprocess a source file
src/hash.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/hash.c.i
.PHONY : src/hash.c.i

src/hash.s: src/hash.c.s
.PHONY : src/hash.s

# target to generate assembly for a file
src/hash.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/hash.c.s
.PHONY : src/hash.c.s

src/lib.o: src/lib.c.o
.PHONY : src/lib.o

# target to build an object file
src/lib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/lib.c.o
.PHONY : src/lib.c.o

src/lib.i: src/lib.c.i
.PHONY : src/lib.i

# target to preprocess a source file
src/lib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/lib.c.i
.PHONY : src/lib.c.i

src/lib.s: src/lib.c.s
.PHONY : src/lib.s

# target to generate assembly for a file
src/lib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/lib.c.s
.PHONY : src/lib.c.s

src/logs.o: src/logs.c.o
.PHONY : src/logs.o

# target to build an object file
src/logs.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/logs.c.o
.PHONY : src/logs.c.o

src/logs.i: src/logs.c.i
.PHONY : src/logs.i

# target to preprocess a source file
src/logs.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/logs.c.i
.PHONY : src/logs.c.i

src/logs.s: src/logs.c.s
.PHONY : src/logs.s

# target to generate assembly for a file
src/logs.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/logs.c.s
.PHONY : src/logs.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/main.c.s
.PHONY : src/main.c.s

src/scannerDefinitions.o: src/scannerDefinitions.c.o
.PHONY : src/scannerDefinitions.o

# target to build an object file
src/scannerDefinitions.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/scannerDefinitions.c.o
.PHONY : src/scannerDefinitions.c.o

src/scannerDefinitions.i: src/scannerDefinitions.c.i
.PHONY : src/scannerDefinitions.i

# target to preprocess a source file
src/scannerDefinitions.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/scannerDefinitions.c.i
.PHONY : src/scannerDefinitions.c.i

src/scannerDefinitions.s: src/scannerDefinitions.c.s
.PHONY : src/scannerDefinitions.s

# target to generate assembly for a file
src/scannerDefinitions.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/scannerDefinitions.c.s
.PHONY : src/scannerDefinitions.c.s

src/semanticError.o: src/semanticError.c.o
.PHONY : src/semanticError.o

# target to build an object file
src/semanticError.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/semanticError.c.o
.PHONY : src/semanticError.c.o

src/semanticError.i: src/semanticError.c.i
.PHONY : src/semanticError.i

# target to preprocess a source file
src/semanticError.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/semanticError.c.i
.PHONY : src/semanticError.c.i

src/semanticError.s: src/semanticError.c.s
.PHONY : src/semanticError.s

# target to generate assembly for a file
src/semanticError.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/semanticError.c.s
.PHONY : src/semanticError.c.s

src/semantics.o: src/semantics.c.o
.PHONY : src/semantics.o

# target to build an object file
src/semantics.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/semantics.c.o
.PHONY : src/semantics.c.o

src/semantics.i: src/semantics.c.i
.PHONY : src/semantics.i

# target to preprocess a source file
src/semantics.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/semantics.c.i
.PHONY : src/semantics.c.i

src/semantics.s: src/semantics.c.s
.PHONY : src/semantics.s

# target to generate assembly for a file
src/semantics.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/semantics.c.s
.PHONY : src/semantics.c.s

src/span.o: src/span.c.o
.PHONY : src/span.o

# target to build an object file
src/span.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/span.c.o
.PHONY : src/span.c.o

src/span.i: src/span.c.i
.PHONY : src/span.i

# target to preprocess a source file
src/span.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/span.c.i
.PHONY : src/span.c.i

src/span.s: src/span.c.s
.PHONY : src/span.s

# target to generate assembly for a file
src/span.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/span.c.s
.PHONY : src/span.c.s

src/symbols.o: src/symbols.c.o
.PHONY : src/symbols.o

# target to build an object file
src/symbols.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/symbols.c.o
.PHONY : src/symbols.c.o

src/symbols.i: src/symbols.c.i
.PHONY : src/symbols.i

# target to preprocess a source file
src/symbols.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/symbols.c.i
.PHONY : src/symbols.c.i

src/symbols.s: src/symbols.c.s
.PHONY : src/symbols.s

# target to generate assembly for a file
src/symbols.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/symbols.c.s
.PHONY : src/symbols.c.s

src/tac.o: src/tac.c.o
.PHONY : src/tac.o

# target to build an object file
src/tac.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/tac.c.o
.PHONY : src/tac.c.o

src/tac.i: src/tac.c.i
.PHONY : src/tac.i

# target to preprocess a source file
src/tac.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/tac.c.i
.PHONY : src/tac.c.i

src/tac.s: src/tac.c.s
.PHONY : src/tac.s

# target to generate assembly for a file
src/tac.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/tac.c.s
.PHONY : src/tac.c.s

src/types.o: src/types.c.o
.PHONY : src/types.o

# target to build an object file
src/types.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/types.c.o
.PHONY : src/types.c.o

src/types.i: src/types.c.i
.PHONY : src/types.i

# target to preprocess a source file
src/types.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/types.c.i
.PHONY : src/types.c.i

src/types.s: src/types.c.s
.PHONY : src/types.s

# target to generate assembly for a file
src/types.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Compiladores.dir/build.make CMakeFiles/Compiladores.dir/src/types.c.s
.PHONY : src/types.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Compiladores"
	@echo "... parser.o"
	@echo "... parser.i"
	@echo "... parser.s"
	@echo "... scanner.o"
	@echo "... scanner.i"
	@echo "... scanner.s"
	@echo "... src/argumentParser.o"
	@echo "... src/argumentParser.i"
	@echo "... src/argumentParser.s"
	@echo "... src/ast.o"
	@echo "... src/ast.i"
	@echo "... src/ast.s"
	@echo "... src/errorHandler.o"
	@echo "... src/errorHandler.i"
	@echo "... src/errorHandler.s"
	@echo "... src/funcCode.o"
	@echo "... src/funcCode.i"
	@echo "... src/funcCode.s"
	@echo "... src/generateAssembly.o"
	@echo "... src/generateAssembly.i"
	@echo "... src/generateAssembly.s"
	@echo "... src/generateCode.o"
	@echo "... src/generateCode.i"
	@echo "... src/generateCode.s"
	@echo "... src/graphBlock.o"
	@echo "... src/graphBlock.i"
	@echo "... src/graphBlock.s"
	@echo "... src/hash.o"
	@echo "... src/hash.i"
	@echo "... src/hash.s"
	@echo "... src/lib.o"
	@echo "... src/lib.i"
	@echo "... src/lib.s"
	@echo "... src/logs.o"
	@echo "... src/logs.i"
	@echo "... src/logs.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/scannerDefinitions.o"
	@echo "... src/scannerDefinitions.i"
	@echo "... src/scannerDefinitions.s"
	@echo "... src/semanticError.o"
	@echo "... src/semanticError.i"
	@echo "... src/semanticError.s"
	@echo "... src/semantics.o"
	@echo "... src/semantics.i"
	@echo "... src/semantics.s"
	@echo "... src/span.o"
	@echo "... src/span.i"
	@echo "... src/span.s"
	@echo "... src/symbols.o"
	@echo "... src/symbols.i"
	@echo "... src/symbols.s"
	@echo "... src/tac.o"
	@echo "... src/tac.i"
	@echo "... src/tac.s"
	@echo "... src/types.o"
	@echo "... src/types.i"
	@echo "... src/types.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

